# Generated by Django 5.1 on 2024-09-19 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='media/event_logos', verbose_name='Логотип')),
                ('event_date', models.DateTimeField(verbose_name='Дата проведения')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объекта')),
                ('location', models.CharField(max_length=123, verbose_name='Место проведения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена билета')),
                ('available', models.PositiveSmallIntegerField(verbose_name='Количество доступных билетов')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('is_active', models.PositiveSmallIntegerField(choices=[(1, 'Активен'), (2, 'Не активен')], default=1, verbose_name='Статус активности')),
                ('is_main', models.PositiveSmallIntegerField(choices=[(1, 'На главную'), (2, 'В каталог')], default=2, verbose_name='Вывод ивента на главную')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во билетов')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В обработке'), (2, 'Оплачен'), (3, 'Произошла ошибка при оплате')], default=1, verbose_name='Статус оплаты')),
                ('ticket_code', models.CharField(max_length=36)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
